# L2X9Core by 254n-m
# Version 4.2.0
# Config Version 1.5.3

#Messages to send the player when they try to place illegal blocks
IllegalBlock-Place:
  Bedrock: '[&b&lL2X9&r&3&lCore&r] &6That block is not allowed'
  Barrier: '[&b&lL2X9&r&3&lCore&r] &6That block is not allowed'
  End_Portal_Frame: '[&b&lL2X9&r&3&lCore&r] &6That block is not allowed'
  Mob_Spawner: '[&b&lL2X9&r&3&lCore&r] &6That block is not allowed'
#ChunkBan skull limit tile entity limit and prevent message
ChunkBan:
  Prevent-Message: '[&b&lL2X9&r&3&lCore&r] &6ChunkBan has been disabled due to an exploit (^:'
  TileEntity-Max: 500
  Skull-Max: 100
#Nether top and bottom layers
Nether:
  Top-Layer: 127
  Top-message: '[&b&lL2X9&r&3&lCore&r] &6The nether top has been disabled due to lag'
  Bottom-Layer: 0
  Bottom-message: '[&b&lL2X9&r&3&lCore&r] &6The nether bottom has been disabled due to lag'
  top-bottom-do-damage: true
#Radius arround spawn to disable /home in 
#Set 0 to disable
Spawn:
  Raidus: 500
  Message: "&6You must be&r&c %r% &r&6 blocks from spawn to use /home "
#Off hand server crash with dupe books messages
Offhand-Server-Crash:
  Shulker-messager: '[&b&lL2X9&r&3&lCore&r] &4No'
  Book-message: '[&b&lL2X9&r&3&lCore&r] &4No'
#Message to send to the server when a player first joins
#Use {Player} as a place holder for the players name
FirstJoin:
   Message: '&c{Player}&r&7 Has joined the server for the first time'
#Elytra/redstone disable TPS value
#Set "40" to disable
Elytra:
   Disable-TPS: 17 
Redstone:
   Disable-TPS: 16
#AntiIllegal enabled true/false
AntiIllegal-Enabled: true
#Anti LightLag
LightingLag-StepIn:
   TPS: 17